### ISSUE TITLE
ADD ON readme the

### ISSUE THREAD

**Issue by PedroMPagani** [mfnalex/CustomBlockData#14]
pros of which is high memory usage if using it on a lot of blocks
it's a new HashMap<>() for every single block, developers don't usually see it this way
and this will cause extremely high memory usages, since this is a library it's good to show them that it's not "good" to use on thousands of blocks... (It's a new HashMap<>() for every single block).

IT creates a new persistent data container to every single block that gets set
this means
it'll allocate a keyspace on the map of teh chunk + create a new full key space for each block:
this is how it ends up being like:
Map<NameKey, PersistContainer>

and each perssist data container has a new Map.
![image](https://github.com/mfnalex/CustomBlockData/assets/56891617/f081a38e-8545-48df-af5a-f09123a79926)

It would be nice to tell the devs about this, reverting the damage frmo this library if used on a lot of spots it's bad.

**Comment by mfnalex** [comment]
IMHO it is pretty obvious that this creates one CraftPersistentDataContainer for each block, after all the CustomBlockData class implements PersistentDataHolder. I am not really sure what the purpose of this issue is supposed to be - maybe you could try to explain again?

**Comment by PedroMPagani** [comment]
> IMHO it is pretty obvious that this creates one CraftPersistentDataContainer for each block, after all the CustomBlockData class implements PersistentDataContainer - and the description says "PersistentDataContainer for blocks". I am not really sure what the purpose of this issue is supposed to be - maybe you could try to explain again?

The reason I ask is because they don't really realize that this will lead to a huge overhead if they're using this on lots of blocks. (Most people won't look at how the library is implemented and will just use it) - I know it is not an excuse. It's just if there was an information about this, people would probably realize faster? oh yeah so I have to avoid using a lot of this because yk.. it'll be persistent and it could be across 100s of thousands of blocks..
